name: windows

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    # Alternative:
    # sudo apt install linux-libc-dev
    # sudo apt-get -f install
    # sudo apt install gcc-4.8

    - name: Update sources to include xenial main
      run: sudo su -c "echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial main' >> /etc/apt/sources.list"

    - name: Update sources to include xenial universe
      run: sudo su -c "echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial universe' >> /etc/apt/sources.list"

    - name: Update packages
      run: sudo apt update -y

    - name: Install make
      run: sudo apt-get install make

    - name: Install g++-4.8
      run: sudo apt install g++-4.8 gcc-4.8 -y

    - name: Install headers
      run: sudo apt-get install gcc-4.8-multilib g++-4.8-multilib -y gcc-mingw-w64
    # windows build is commented   
    - name: Windows build 
      run: make OSTYPE=win32
    - name: Create asset
      run: |
          tar c addons | xz > jk_botti-${{ steps.get_version.outputs.VERSION  }}-release.tar.xz
    - name: Upload build result
      uses: actions/upload-artifact@v3.1.2
      with:
          name: jk_botti-${{ steps.get_version.outputs.VERSION  }}-release.tar.xz
          path: ./jk_botti-${{ steps.get_version.outputs.VERSION  }}-release.tar.xz
