name: windows


on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0
    - name: Update package list for i386
      run: sudo dpkg --add-architecture i386 && sudo apt-get -y update
    - name: Install packages
      run: sudo apt-get -y install build-essential g++-multilib gcc-mingw-w64 g++
    # windows build is commented   
    - name: Windows build 
      run: make OSTYPE=win32
    - name: Create asset
      run: |
          tar c addons | xz > jk_botti-${{ steps.get_version.outputs.VERSION  }}-release.tar.xz
    - name: Upload build result
      uses: actions/upload-artifact@v3.1.2
      with:
          name: jk_botti-${{ steps.get_version.outputs.VERSION  }}-release.tar.xz
          path: ./jk_botti-${{ steps.get_version.outputs.VERSION  }}-release.tar.xz
