name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update package list for i386
      run: sudo dpkg --add-architecture i386 && sudo apt-get -y update
    - name: Install packages
      run: sudo apt-get -y install build-essential g++-multilib gcc-mingw-w64 g++-mingw-w64
    - name: Linux build
      run: make
    - name: Rename Linux build output
      run: mv addons addons-linux
    - name: cleanup 1
      run: git clean -xdf
    - name: Windows build
      run: make OSTYPE=win32
    - name: Rename Windows build output
      run: mv addons addons-windows
    - name: Create asset
      run: |
          tar c addons-linux addons-windows | xz > jk_botti-${{ github.sha }}-release.tar.xz
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
          name: jk_botti-${{ github.sha }}-release.tar.xz
          path: ./jk_botti-${{ github.sha }}-release.tar.xz
